### ISSUE TITLE
Web Version?

### ISSUE THREAD

**Issue by MgSam** [FlashpointProject/launcher#219]
Apologies in advance if this isn't the right place to ask this. 

Is it feasible to host a version of this app on the web? I see it uses Electron already. This is the best and most complete collection of Flash games I've seen, and I think it would be most accessible to the world from a website rather than desktop software (though the software is fantastic).

**Comment by lino-levan** [comment]
I want to preface this by saying that I am not a developer of the project, but I have been following it for a while. As far as I know, it is currently (not-withstanding any huge changes to web APIs) infeasible due to the need to set up a proxy to access the flash games. This proxy afaik is necessary to get around the website lock that happens in a large number of flash games.  This is probably the least of the issues (you still need to RUN the flash games which obviously is going to be a nightmare considering the support of flash) but this at least renders it impossible to host something like this online.

I apologize for the rant-y response.

**Comment by MgSam** [comment]
Ah, so Electron is just the shell and the games themselves are actually just running on Flex or something? I'm by no means an expert, but given all the stuff that's been cross-compiled to WASM in the past decade I'd hope that at some point a project like this could make a similar leap. Obviously running as native Flash in the browser is now infeasible.

**Comment by TBubba** [comment]
It would be possible (and it used to be at some point) to run the launchers interface in a browser, but it still required you to download and run the launcher program. It was mostly an experiment and turned out to be pretty useless so we just stopped supporting it (if I recall correctly).

@lino-levan is correct about what makes it not possible to run the entire thing in a browser. Keep in mind that the whole reason this project is that modern and up-to-date browsers are no longer able to run this stuff.

This might change in the future depending on if anyone develops emulators etc. (such as [Ruffle](https://github.com/ruffle-rs/ruffle)).
