### ISSUE TITLE
[BUG] Flashpoint 10.1.1 | Manjaro Linux | unable to launch/download games.

### ISSUE THREAD

**Issue by Xeddius** [FlashpointProject/launcher#281]
Starting the launcher works fine, images are loading fine (after setting proper directory in config), however upon attempting to load any game nothing happens.

In the developer tab under Server and Apache Server these are the two logs I'm seeing and they aren't very descriptive.

**Server:**
```
[21:05:30] Server has been started
[21:05:30] Server failed to start - spawn httpd ENOENT
```

**Apache:**
```
[21:05:30] Apache Webserver has been started
[21:05:30] qemu-system-i386: Machine type received is 'pc-i440fx-6.0' and local is 'pc-i440fx-6.1'
[21:05:30] qemu-system-i386: Error -22 while loading VM state
[21:05:30] Apache Webserver exited with code 1
```

Latest version of Flashpoint and Manjaro (everything is up to date.)

EDIT: The temporary fix for this is by using MAD4FP and changing services.json (located in DATA folder) to match below:
```
{
  "watch": [
    "<fpPath>/Legacy/logs/access.log"
  ],
  "server": [
    {
      "name": "PHP Router",
      "path": "Legacy",
      "filename": "php",
      "arguments": ["-S", "127.0.0.1:22600", "router.php"],
      "kill": true
    },
    {
      "name": "MAD4FP Mode",
      "path": "Legacy",
      "filename": "php",
      "arguments": ["-S", "127.0.0.1:22600", "router_mad4fp.php"],
      "kill": true,
      "mad4fp": true
    },
    {
      "name": "Legacy Webserver",
      "path": "Legacy",
      "filename": "httpd",
      "arguments": ["-f", "<fpPath>/Legacy/conf/httpd.conf", "-X"],
      "kill": true
    }
  ],
  "daemon": [
    {
      "name": "Apache Webserver",
      "path": "Server",
      "filename": "qemu-system-i386",
      "arguments": ["-machine", "pc-i440fx-6.0", "-m", "512", "-net", "nic,model=e1000", "-net", "user,hostfwd=tcp:127.0.0.1:22500-:80", "-qmp", "tcp:127.0.0.1:4444,server,nowait", "-qmp", "tcp:127.0.0.1:4445,server,nowait", "-hda", "alpine.qcow2", "-loadvm", "quick", "-display", "none"],
      "kill": true
    }
  ],
  "start": [
    {
      "path": "Legacy",
      "filename": "php",
      "arguments": ["-f", "update_httpdconf_main_dir.php"]
    }
  ],
  "stop": [
    {
      "path": "Legacy",
      "filename": "php",
      "arguments": ["-f", "reset_httpdconf_main_dir.php"]
    }
  ]
}

```
However some games still do not download and will simply fail to launch as Flashpoint tries to load an already downloaded file despite the fact that it never downloaded anything to begin with. There should be a manual "download" button or the ability to select/mark games for download. A simple download manager would be a nice feature and would fix this issues.

**Comment by insomniacUNDERSCORElemon** [comment]
I don't know if it's known or platform-specific, but enabling native platforms (for Flash, HTML5, Java) does not work for me w/Arch Linux. Maybe this is because "available" to Flashpoint means if it's shipped by+configured in Flashpoint?

For the non-legacy stuff that will actually download properly, those can often be launched manually (via file browser) to work... particularly with most Flash games. I'd imagine a lot of HTML5 games that use WEBGL (and thus cannot be loaded from file://) would work this way manually too by running the 1-line simple server via Python (`python -m http.server 8000
`). Would be nice if Flashpoint could at least run the non-site-locked content so stuff like this wasn't needed.

**Comment by LindirQuenya** [comment]
The first error means that you don't have apache installed, and/or it isn't symlinked to httpd. This isn't a problem, because you shouldn't be using the legacy webserver anyway. Switch your setting from "Legacy Webserver" to "PHP router" in the config tab, and use the "Save and Restart" button to update the config. Note that you will need PHP installed.

The second error can be fixed by adding "-machine", "pc-i440fx-6.0" to the arguments list for the gamezip server, as you found. This one is a [known problem](https://bluemaxima.org/flashpoint/datahub/Linux_Support#Fix_qemu_failing_to_start), and we will hopefully fix it in the next release, albeit with "pc-i440fx-5.2", because we want compatibility with older QEMU versions.

**Comment by insomniacUNDERSCORElemon** [comment]
Changing the Qemu line worked for me (still not honoring native application settings, though), although now I'm seeing that the issue with legacy content seems that it's configured to *not* save, so if it can't download fast enough it just gives `exited with signal null`. 

I say that particularly because if I can find legacy content that is small enough for my 6Mbps internet to download in time, even while running it says there is no file (so it seems to just run in memory).

**Comment by LindirQuenya** [comment]
Huh. What version are you on? I know that the current manual installation doesn't include the native projectors or browser, which is something that will be solved in maybe a month or two when fpdocker is ready for primetime.

I don't know about that download problem. I know that it's not retrieved from the source, but rather from dri0m's servers. Are you on the Flashpoint discord server? Perhaps people there can help you.

**Comment by insomniacUNDERSCORElemon** [comment]
> What version are you on?

 I just updated my system and that seemed to fix both legacy-content issues (some files not working, working stuff not being saved) and more. The launcher didn't work at first after updating, I did a force-install but cancelled and it worked after that.

Though I'm not sure if those were just old issues or if it was some other incompatibility (something like the file list in my version being out-of-date).
