### ISSUE TITLE
[BUG] App cannot be launched with a non-admin account and finder

### ISSUE THREAD

**Issue by UnrelatedWorks** [FlashpointProject/launcher#371]
**Describe the bug**
Flashpoint can only be launched with admin privileges 

**To Reproduce**
1. Go to '/Applications Folder'
2. Click on 'Flashpoint.app'

**Expected behavior**
WindowServer displays the Application

**Screenshots**
<img width="2219" alt="Screenshot 2022-08-02 at 14 22 33" src="https://user-images.githubusercontent.com/91271174/182375668-31c87142-0e24-4055-b243-8d70ef62340f.png">
<img width="290" alt="Screenshot 2022-08-02 at 13 59 02" src="https://user-images.githubusercontent.com/91271174/182375698-0d603f54-291b-4965-880b-69516107ace8.png">

**Desktop (please complete the following information):**
 - OS: OS Monterey 12.4, M1
 - Flashpoint Version 10.1.4
 - Log text see screenshot

**Comment by n0samu** [comment]
The reason this happens is that the preferences file is missing on first startup, not that you lack admin privileges. This is a bug that should be fixed though, since the launcher is supposed to automatically create a preferences file and load it without crashing. But of course this bug will not affect actual Flashpoint distributions since they come with a preferences file preinstalled.

**Comment by UnrelatedWorks** [comment]
I understand the preference situation. I just was under the impression that the launcher requires escalated privileges to write the pref file. (osX is pretty strict sometimes) 
Can you elaborate what the "actual Flashpoint distros" are? I know that the website does not have the .dmg files. The sample I have is from the official GitHub [here](https://github.com/FlashpointProject/launcher/releases). I didn't compile the app myself.

**Comment by n0samu** [comment]
> I just was under the impression that the launcher requires escalated privileges to write the pref file.

Oh I see what happened, you placed Flashpoint Launcher directly in your Applications folder, which I don't blame you for as that's what you do to install most Mac apps. But Flashpoint Launcher stores its preferences next to the application, and writing to the root of the Applications folder requires administrative privileges. You can create a Flashpoint subfolder inside your Applications folder and place the Launcher there to avoid this problem.

> Can you elaborate what the "actual Flashpoint distros" are?

I mean https://bluemaxima.org/flashpoint/downloads/ , or for MacOS, https://bluemaxima.org/flashpoint/datahub/Mac_Support#Installing_Flashpoint . Flashpoint Launcher is just part of the larger Flashpoint package that we distribute, it's not really meant to be used on its own.

**Comment by UnrelatedWorks** [comment]
Makes sense. The website only shows the .exe to download. 
If interested, I can work on a 2 button solution for the website (windows/Mac) when downloading infinity. The Mac version would simply download the script which then can be executed, no copy and paste or messing with the terminal. 
You can close the ticket.

**Comment by n0samu** [comment]
> If interested, I can work on a 2 button solution for the website (windows/Mac) when downloading infinity. The Mac version would simply download the script which then can be executed, no copy and paste or messing with the terminal.

The problem is that if you have a user download any executable from their browser, it will have a piece of metadata attached to it indicating that it came from the Internet, and Gatekeeper will block it. The only way we can get around Gatekeeper is having the user run something themself via the Terminal, using cURL to download Flashpoint in a way that does not set that piece of metadata and thus evades Gatekeeper. As far as I understand, the only other solution is to pay Apple $99 a year for the privilege of not having your software blocked, which doesn't seem like a great investment to me.
