### ISSUE TITLE
is it possible to have Mac version of it?

### ISSUE THREAD

**Issue by zzz6519003** [FlashpointProject/launcher#88]

**Comment by TBubba** [comment]
It certainly is possible to get the launcher working on Mac. But I'm not sure how many of the "technologies" (Flash, Unity, ActiveX etc.) will work on Mac.

We have done some work in the past to make the launcher work on Mac. But since we don't own any machines ourselves, we have relied on volunteers to try debug builds and report any bugs and errors.

With that said, we would be interested in getting it to work on Mac.

**Comment by zzz6519003** [comment]
plus the opengl thing? XD

**Comment by zzz6519003** [comment]
geek use Mac, and they love games
